# Generated by Django 3.2.4 on 2021-06-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_auto_20210622_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_bestlling_book',
            new_name='is_bestselling_book',
        ),
    ]
